apollographql/graphql-subscriptions

package.json, src/index.ts, src/pubsub.ts, src/test/tests.ts, typings.json
Hi @helfer,
This PR is to allow PubSub managers like redis pubsub or any other event source that cannot be run on the same process as the graphql-subscriptions process.
I've updated the tests and the EventEmitter based PubSubEngine to just Promise.resolve the given subscription id so it will behave the same as before.
Also wrote a redis PubSub Engine to go along with this PR - https://github.com/davidyaha/graphql-redis-subscriptions
Thanks ahead,
David
=> Support async subscribe method (or other PubSub engine methods)

package.json, src/index.ts, src/pubsub.ts, src/test/tests.ts
* Moved filter functionality to the SubscriptionsManager.
* Added pubsub argument to SubscriptionManager to allow for different kinds of PubSub Engines
* Updated typescript dependencies to 2.0.0 to allow for the current graphql typings to work. see https://github.com/Microsoft/TypeScript/issues/7279
=> Allow replacing of the PubSub engine

package.json, src/pubsub.ts, src/test/tests.ts, typings.json
See #10 for previous communication. Solves #7. 
This change requires a setup function to return an object containing the properties `filter` and `channelOptions`. Both are optional, so no breaking changes in that regard. However, there is no backwards compatibility for the "old style" function-type return value, so existing usages need to be updated to return an object with `filter` property.
Code example taken from #10, adapted to object-style return value:
```javascript
{
setupFunctions: {
// Taken from GitHunt.
commentAdded: (options, args) => ({
commentAdded: {
filter: comment => comment.repository_name === args.repoFullName
}
}),
// Proposed structure.
commentUpdated: (options, args) => ({
commentUpdated: {
// These options could be passed to PubSub.
channelOptions: {
repoFullName: …
```
=> Make a setupFunction return an object

src/pubsub.ts, src/test/tests.ts
The idea behind this change is to support a distinct context for each processed message. The idea is to mirror the per HTTP request GraphQL context creation flow. Currently the context is fixed on the SubscriptionManager when the initial publish is created and is also used to create the triggerMap. The API change adds `createContext: Function` to SubscriptionOptions. If specified the new context is passed to `filter` and `onMessage`.
=> Allow context to be a function that is called per message

AUTHORS, LICENSE, README.md
Updated README with license & npm badges on the way
(Assumed same state as apollostack/subscriptions-transport-ws#37)
=> Added license & authors files

src/pubsub.ts, src/test/tests.ts
- technically, UT was passing before the change, because PubSub was throwing
- as the subscriptions list isn't public, I can't test the leak alone
- fixes #14
=> Fix subscription leak, added UT

package.json
Also updated the dependency to the latest release of `graphql`.
=> Moved graphql to a peer-dependency

src/pubsub.ts
I'm not a Promise expert, but the previous code at least read like it was
possible for the Promise returned by subscribe to resolve once all the
this.pubsub.subscribe Promises resolved but before all of the "push onto
this.subscriptions" Promises resolved.  If unsubscribe was called too quickly,
you could in theory end up calling one of those "push" functions after the
`delete this.subscriptions[subId]` line and crashing.
In practice the old code does appear to work but this code more accurately shows
the intentions.
@benjamn this is the code I asked you for advice on, thanks!
=> Wait on correct Promise in subscription

src/pubsub.ts
This is a super simple change, with the major benefit being that pubsub can `.then` onto the returned promise from the `onMessage` handler to do interesting things like instrument the time it took to perform a subscription.
=> Return the promise from onMessage

AUTHORS, CHANGELOG.md, src/pubsub.ts, src/test/tests.ts
@helfer This was the changed I mentioned to allow the filter function to be async.
=> allow the filter function to be async

package.json, src/test/asyncIteratorSubscription.ts, src/with-filter.ts
This PR fixes #73 (and possibly https://github.com/apollographql/subscriptions-transport-ws/issues/154)
`withFilter` is a wrapper around an asyncIterator, providing filtering of subsequent values.
When a graphql subscription is ended, graphql-js will either call `return()` or `throw()` on all related asyncIterators.
Current implementation of `withFilter` would not propagate those calls to the wrapped asyncIterator resulting in event handlers not being properly unregistered and nasty memory leak :skull:.
This PR fixes this behaviour by making `withFilter` call the relevant method on the underlying asyncIterator.
Bugfix implementation is trivial, `withFilter` now correctly acts as a proxy to the original asyncIterator.
I'm a bit more concerned about the test implementation. I chose to …
=> Properly propagate return() and throw() through withFilter

README.md
VS Code removed some trailing spaces. Hope you weren't too fond of them.
=> Added graphql-kafka-subscriptions link in the readme

README.md
Based on [this StackOverflow answer](https://stackoverflow.com/a/43790449/2115623) by @helfer I've added a pretty important note to the README that the default `PubSub` implementation should not be used in production.
I did not realise this and have been running it in production across multiple instances for months now. We've had memory leak warnings and all that, but couldn't pinpoint the source until I randomly stumbled upon that StackOverflow answer. In hindsight it's obvious, but when you're in the middle of a huge codebase with complex real-time requirements it's not obvious at all.
=> Add note about production usage of the default PubSub implementation

package.json
=> Remove `es6-promise`.

README.md
This should help prevent the confusion described in https://github.com/apollographql/graphql-subscriptions/issues/113 and https://github.com/apollographql/graphql-subscriptions/issues/130
People copy/pasting the example would previously break their working subscription.
I must say it's not very DRY to setup a subscription like this...
=> Document getting payload value in sub resolve

README.md
I just published [`callback-to-async-iterator`](https://github.com/withspectrum/callback-to-async-iterator) based on the Event Emitter to Async Iterator module used in graphql-js. Having struggled with this a fair bit, I think a lot of people would appreciate the note on how to work with async iterators!
=> Add note about callback listeners

README.md
Hi everyone!
I wanted to use subscriptions and already had setup a Postgres DB for persistence. I realized there was no Postgres subscriptions adapter so I set out to create one. It's based on Postgres' [`NOTIFY`](https://www.postgresql.org/docs/9.0/static/sql-notify.html) and [`LISTEN`](https://www.postgresql.org/docs/9.0/static/sql-listen.html). Take a look at it in https://github.com/GraphQLCollege/graphql-postgres-subscriptions.
Thanks for making it really easy to add new adapters! I based the postgres adapter on your PubSub adapter. It has some integration tests to make sure it works fine.
I hope you think it looks good and is worth accepting! If you have any suggestions I'll gladly work on them.
Thanks for making such awesome open source tools!
=> Add link to graphql-postgres-subscriptions in README

package.json
We're making the gradual transition to graphql 14 across all Apollo projects. This PR:
- Allows `graphql` 14 as a peer dep
- Forces `graphql` 14 as a dev dep
- Updates to `@types/graphql` 14
=> `graphql` 14.x updates

.travis.yml, CHANGELOG.md, package.json
@NeoPhi I'd like to push out a new `graphql-subscriptions` release as soon as possible (to get the changes from https://github.com/apollographql/graphql-subscriptions/pull/171 in place). I see in the changelog that there is currently a breaking change waiting to be released. Do you have any issues with me bumping to 1.0.0 and publishing? Thanks!
=> Version bump and changelog updates, prepping for release

README.md
Not a big thing. Based on above context
```js
const listenToNewMessages = (callback) => {
return db.table('messages').listen(newMessage => callback(newMessage));
}
// Kick off the listener
listenToNewMessages(message => {
console.log(message);
})
```
`listenToNewMessages` is a better fit.
=> doc: update demo code

package.json, src/test/asyncIteratorSubscription.ts, src/with-filter.ts, tsconfig.json
`withFilter` function is causing memory leak because of Promise spec. Related: https://github.com/nodejs/node/issues/6673.
This is a big problem when you have long living subscriber to subscription who skips most of messages (all Promises in recursion chain are kept in memory).
**How to reproduce:**
Start a subscriber to a subscription which rejects messages and start publishing messages. You'll notice memory keeps increasing. Memory profile will confirm.  
Do the same thing using refactored `withFilter` and you'll notice memory is not increasing.
**Pull Request Labels**
Fixes #212
=> Fix memory leak in withFilter cause by recursion

package.json
When installing via GitHub e.g. `npm i github:apollographql/graphql-subscriptions#master` the dist directory isn't created as the prepare script is missing. This add it.
=> fix: installing via git not creating dist

README.md
[Ably](https://www.ably.io) is a pub/sub messaging platform with a suite of integrated services and cross-protocol and cross-platform support to deliver realtime messages. In the context of GraphQL, we can use it to publish when a mutation is fired and subscribe to the result through a subscription query.
The linked package implements the PubSubEngine Interface from the graphql-subscriptions package and also the new AsyncIterator interface. It allows you to connect your subscription manger to an Ably PubSub mechanism to support multiple subscription manager instances.
[NPM package](https://www.npmjs.com/package/graphql-ably-pubsub)
=> docs(README): Add link for Ably PubSub implementation

README.md
Original author of the library stopped maintaining it and it is no longer supporting latest versions of GraphQL
=> fix: Update to the library fork that is maintained

CHANGELOG.md, src/with-filter.ts
Adds TypeScript support for the with filter function. Should be backward compatible.
=> Add TypeScript support to withFilter

CHANGELOG.md, README.md, src/pubsub.ts
The class PubSub now has a generic type parameter so its methods `publish` and `subscribe` can be **optionally** type-checked by TypeScript.
/label typedefs
I was using [`apollo-server-express`](https://www.npmjs.com/package/apollo-server-express) but the class `PubSub` did not have any compile time validation by TypeScript. So I extended the class and added a generic. I thought I would contribute to the project back since it will be useful to others.
New usage:
```ts
import { PubSub } from "apollo-server-express";
const pubsub = new PubSub<{
EVENT_ONE: { data: number; };
EVENT_TWO: { data: string; };
}>();
pubsub.publish("EVENT_ONE", { data: 42 });
pubsub.publish("EVENTONE", { data: 42 }); // ! ERROR
pubsub.publish("EVENT_ONE", { data: "42" }); // ! ERROR
pubsub.publish("EVENT_TWO", { …
```
=> Add a(n optional) generic type map to PubSub.

CHANGELOG.md, package.json, src/pubsub-async-iterable-iterator.ts, src/pubsub-engine.ts, src/test/asyncIteratorSubscription.ts, src/test/tests.ts, src/with-filter.ts
**BREAKING** fixes the type annotation of the abstract class PubSubEngine. According to the TypeScript type-defintion a `PubSubAsyncIterator` instance is actually an `AsyncIterableIterator` instead of an  `AsyncIterator`. The typing of `PubSubAsyncIterator` is way more convenient as it allows iterating over it with the `for await (const foo of iterator) { doSth() }` syntax, which is super handy for filtering or mapping (See https://gist.github.com/n1ru4l/127178705cc0942cad0e45d425e2eb63 for some example operators).
This should be able to get merged once Node.js 10 runs out of LTS. See https://nodejs.org/en/about/releases/
Technically this project already dropped Node.js 10 support when removing the Node.js 10 CI build.
Closes https://github.com/apollographql/graphql-subscriptions/issues/19 …
=> feat: replace iterall with native Symbol.asyncIterator + fix return types

CHANGELOG.md, src/pubsub-async-iterable-iterator.ts, src/pubsub-engine.ts, src/test/tests.ts
**BREAKING** Allow a `readonly` topics / events array to be passed to `PubSubEngine.asyncIterator()`. I think this is how any well-behaved implementation should treat the incoming array anyway, and it would allow read-only arrays to be accepted upstream (eg https://github.com/MichalLytek/type-graphql/pull/718)
I believe this is (minor) breaking because it could mean downstream subclasses of `PubSubEngine` re-implement `asyncIterator` with incompatible types. It might be best paired with https://github.com/apollographql/graphql-subscriptions/pull/232 ?
=> fix: Support readonly arrays as event names

CHANGELOG.md, README.md, src/test/asyncIteratorSubscription.ts, src/test/tests.ts, src/with-filter.ts
Looking at some possible downstream consumers, these seems fine and not breaking since they can receive an async subscription function:
- https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.d.ts#L42-L51
- https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L69-L78
fixes #213
=> Allow resolver fn to be async

README.md
Added AWS SNS + SQS PubSub Implementation.
Agreed with  https://contribute.apollographql.com/.
[NPM Package](https://www.npmjs.com/package/graphql-snssqs-subscriptions)
=> Adds AWS SNS SQS PubSub Implementation

src/index.ts, src/test/tests.ts, src/with-filter.ts
Subscriptions require an AsyncIterable, but withFilter was returning an AsyncIterator. This updates the type of withFilter to acknowledge it returns a type which is both an AsyncIterable and an AsyncIterator.
=> Make WithFilter output type compatible with Apollo Server subscriptions

package.json
Bump the package version to 3.0.0 and fix the repository information to use the new project (apollostack -> apollographql).
=> Bump version and fix repository info in package.json
